# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Ui_NewConnDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnDialog(object):
    def setupUi(self, ConnDialog):
        ConnDialog.setObjectName("ConnDialog")
        ConnDialog.resize(520, 284)
        self.pushButton_test = QtWidgets.QPushButton(ConnDialog)
        self.pushButton_test.setGeometry(QtCore.QRect(250, 220, 80, 27))
        self.pushButton_test.setObjectName("pushButton_test")
        self.pushButton_save = QtWidgets.QPushButton(ConnDialog)
        self.pushButton_save.setGeometry(QtCore.QRect(340, 220, 80, 27))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_cancle = QtWidgets.QPushButton(ConnDialog)
        self.pushButton_cancle.setGeometry(QtCore.QRect(430, 220, 80, 27))
        self.pushButton_cancle.setObjectName("pushButton_cancle")
        self.pushButton_open = QtWidgets.QPushButton(ConnDialog)
        self.pushButton_open.setGeometry(QtCore.QRect(30, 220, 80, 27))
        self.pushButton_open.setObjectName("pushButton_open")
        self.splitter = QtWidgets.QSplitter(ConnDialog)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 451, 194))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_conname = QtWidgets.QLabel(self.layoutWidget)
        self.label_conname.setObjectName("label_conname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_conname)
        self.lineEdit_conname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_conname.setObjectName("lineEdit_conname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_conname)
        self.label_hostname = QtWidgets.QLabel(self.layoutWidget)
        self.label_hostname.setObjectName("label_hostname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_hostname)
        self.lineEdit_hostname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_hostname.setObjectName("lineEdit_hostname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_hostname)
        self.label_port = QtWidgets.QLabel(self.layoutWidget)
        self.label_port.setObjectName("label_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_port)
        self.label_username = QtWidgets.QLabel(self.layoutWidget)
        self.label_username.setObjectName("label_username")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_username)
        self.lineEdit_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_user)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.gridLayout.addLayout(self.formLayout, 0, 2, 1, 1)
        self.listWidget_conn = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_conn.setStyleSheet("")
        self.listWidget_conn.setObjectName("listWidget_conn")
        self.gridLayout.addWidget(self.listWidget_conn, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_new = QtWidgets.QPushButton(ConnDialog)
        self.pushButton_new.setGeometry(QtCore.QRect(120, 220, 80, 27))
        self.pushButton_new.setObjectName("pushButton_new")

        self.retranslateUi(ConnDialog)
        self.pushButton_cancle.clicked.connect(ConnDialog.reject)
        self.listWidget_conn.itemClicked['QListWidgetItem*'].connect(ConnDialog.editConn)
        self.listWidget_conn.itemDoubleClicked['QListWidgetItem*'].connect(ConnDialog.openDbFast)
        self.pushButton_new.clicked.connect(ConnDialog.newConn)
        self.pushButton_open.clicked.connect(ConnDialog.openDb)
        self.pushButton_save.clicked.connect(ConnDialog.saveConn)
        self.pushButton_test.clicked.connect(ConnDialog.testConnect)
        self.listWidget_conn.customContextMenuRequested['QPoint'].connect(ConnDialog.rightClick)
        QtCore.QMetaObject.connectSlotsByName(ConnDialog)

    def retranslateUi(self, ConnDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnDialog.setWindowTitle(_translate("ConnDialog", "Jisql-新建链接"))
        self.pushButton_test.setText(_translate("ConnDialog", "连接测试"))
        self.pushButton_save.setText(_translate("ConnDialog", "保存"))
        self.pushButton_cancle.setText(_translate("ConnDialog", "取消"))
        self.pushButton_open.setText(_translate("ConnDialog", "打开"))
        self.label_conname.setText(_translate("ConnDialog", "链接名:"))
        self.lineEdit_conname.setPlaceholderText(_translate("ConnDialog", "本地链接"))
        self.label_hostname.setText(_translate("ConnDialog", "主机名或者IP:"))
        self.lineEdit_hostname.setPlaceholderText(_translate("ConnDialog", "127.0.0.1"))
        self.label_port.setText(_translate("ConnDialog", "端口:"))
        self.lineEdit_port.setPlaceholderText(_translate("ConnDialog", "3306"))
        self.label_username.setText(_translate("ConnDialog", "用户名:"))
        self.lineEdit_user.setPlaceholderText(_translate("ConnDialog", "root"))
        self.label_password.setText(_translate("ConnDialog", "密码:"))
        self.lineEdit_password.setPlaceholderText(_translate("ConnDialog", "root"))
        self.pushButton_new.setText(_translate("ConnDialog", "新建"))

